# Tests Generated by Duo

"""
Tests for calculadora.py
Testing dividir() and es_mayor_de_edad() functions
"""

import pytest
from S7.calculadora import dividir, es_mayor_de_edad


class TestDividir:
    """Test suite for the dividir function"""
    
    # Valid division operations
    def test_dividir_enteros_positivos(self):
        """Test division of positive integers"""
        assert dividir(10, 2) == 5.0
        assert dividir(15, 3) == 5.0
    
    def test_dividir_con_flotantes(self):
        """Test division with float numbers"""
        assert dividir(10.5, 2.0) == 5.25
        assert dividir(7.5, 2.5) == 3.0
    
    def test_dividir_mixto_int_float(self):
        """Test division mixing int and float"""
        assert dividir(10, 2.5) == 4.0
        assert dividir(7.5, 3) == 2.5
    
    def test_dividir_numeros_negativos(self):
        """Test division with negative numbers"""
        assert dividir(-10, 2) == -5.0
        assert dividir(10, -2) == -5.0
        assert dividir(-10, -2) == 5.0
    
    def test_dividir_cero_entre_numero(self):
        """Test dividing zero by a number"""
        assert dividir(0, 5) == 0.0
        assert dividir(0, -3) == 0.0
    
    def test_dividir_resultado_decimal(self):
        """Test division resulting in decimal"""
        assert dividir(10, 3) == pytest.approx(3.333333, rel=1e-5)
        assert dividir(1, 3) == pytest.approx(0.333333, rel=1e-5)
    
    # Type validation tests
    def test_dividir_primer_parametro_string(self):
        """Test that string as first parameter raises TypeError"""
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir("10", 2)
    
    def test_dividir_segundo_parametro_string(self):
        """Test that string as second parameter raises TypeError"""
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir(10, "2")
    
    def test_dividir_ambos_parametros_string(self):
        """Test that strings as both parameters raise TypeError"""
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir("10", "2")
    
    def test_dividir_parametro_none(self):
        """Test that None as parameter raises TypeError"""
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir(None, 2)
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir(10, None)
    
    def test_dividir_parametro_lista(self):
        """Test that list as parameter raises TypeError"""
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir([10], 2)
        with pytest.raises(TypeError, match="a y b deben ser números"):
            dividir(10, [2])
    
    def test_dividir_parametro_booleano(self):
        """Test that boolean as parameter raises TypeError"""
        # Note: In Python, bool is a subclass of int, so True/False are valid
        # This test documents the current behavior
        assert dividir(True, True) == 1.0  # True == 1, False == 0
        assert dividir(10, True) == 10.0
    
    # Division by zero tests
    def test_dividir_entre_cero_entero(self):
        """Test that division by zero raises ValueError"""
        with pytest.raises(ValueError, match="No se puede dividir para cero"):
            dividir(10, 0)
    
    def test_dividir_entre_cero_float(self):
        """Test that division by 0.0 raises ValueError"""
        with pytest.raises(ValueError, match="No se puede dividir para cero"):
            dividir(10, 0.0)
    
    def test_dividir_cero_entre_cero(self):
        """Test that 0/0 raises ValueError"""
        with pytest.raises(ValueError, match="No se puede dividir para cero"):
            dividir(0, 0)
    
    def test_dividir_numeros_muy_pequenos(self):
        """Test division with very small numbers"""
        assert dividir(1e-100, 1e-50) == pytest.approx(1e-50, rel=1e-5)

class TestEsMayorDeEdad:
    """Test suite for the es_mayor_de_edad function"""
    
    # Valid age checks
    def test_edad_menor_de_18(self):
        """Test that ages under 18 return False"""
        assert es_mayor_de_edad(0) is False
        assert es_mayor_de_edad(1) is False
        assert es_mayor_de_edad(10) is False
        assert es_mayor_de_edad(17) is False
    
    def test_edad_exactamente_18(self):
        """Test that age 18 returns True"""
        assert es_mayor_de_edad(18) is True
    
    def test_edad_mayor_de_18(self):
        """Test that ages over 18 return True"""
        assert es_mayor_de_edad(19) is True
        assert es_mayor_de_edad(25) is True
        assert es_mayor_de_edad(50) is True
        assert es_mayor_de_edad(100) is True
    
    # Type validation tests
    def test_edad_float_rechazado(self):
        """Test that float age raises TypeError"""
        with pytest.raises(TypeError, match="La edad debe ser un entero"):
            es_mayor_de_edad(18.0)
        with pytest.raises(TypeError, match="La edad debe ser un entero"):
            es_mayor_de_edad(17.5)
    
    def test_edad_string_rechazado(self):
        """Test that string age raises TypeError"""
        with pytest.raises(TypeError, match="La edad debe ser un entero"):
            es_mayor_de_edad("18")
    
    def test_edad_none_rechazado(self):
        """Test that None as age raises TypeError"""
        with pytest.raises(TypeError, match="La edad debe ser un entero"):
            es_mayor_de_edad(None)
    
    def test_edad_lista_rechazado(self):
        """Test that list as age raises TypeError"""
        with pytest.raises(TypeError, match="La edad debe ser un entero"):
            es_mayor_de_edad([18])
